# Generated by Django 3.1 on 2020-08-22 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=50)),
                ('aboutme', models.TextField(default=None)),
                ('profileimageurl', models.TextField(default=None)),
                ('blogswritten', models.PositiveIntegerField(default=0)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('token', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_id', to='api.users')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_id', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogimageurl', models.TextField()),
                ('title', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='public', max_length=50)),
                ('writtenby', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
