# Generated by Django 3.1 on 2020-08-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
