# Generated by Django 3.1 on 2020-08-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.groups')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
