# Generated by Django 3.1 on 2020-08-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_private_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='private_blogs',
            new_name='blogs_to_groups',
        ),
    ]
